### ISSUE TITLE
Epoch fail: Tectonic doesn't know what day it is called

### ISSUE THREAD

**Issue by jpgoldberg** [lbeckman314/mdbook-latex#6]
My documents are coming out with an Epoch Fail. That is with dates of December 31, 1969.

If I manually run tectonic on the generated LaTeX, I do not encounter that problem. I don't know whether the fix is needed here or in tectonic, but you are the lucky winner of this issues as this is where I am encountering it.

**Comment by lbeckman314** [comment]
Thanks for reporting — I will take a look at this peculiar date issue.
