### ISSUE TITLE
`custom-template` does not seem to work

### ISSUE THREAD

**Issue by jpgoldberg** [lbeckman314/mdbook-latex#7]
I know that this feature is undocumented, but it would be incredibly useful for me right now. From reading the code, it looks like it should work, so perhaps I am calling it incorrectly. Below is the contents of my test book, from which the generated `.tex` file uses the standard template instead of my template. It also does not spit out any errors.

----

```rust
#[serde(default, rename_all = "kebab-case")]
pub struct LatexConfig {
   
    // other fields skipped 

    // Use user's LaTeX template file instead of default (template.tex).
    pub custom_template: Option<String>,
}

```

And this is later used with

```rust
// Copy template data into memory.
    let mut template = if let Some(custom_template) = cfg.custom_template {
            let mut custom_template_path = ctx.root;
            custom_template_path.push(custom_template);
            std::fs::read_to_string(custom_template_path)?
        } else {
            include_str!("template.tex").to_string()
        };
```

This all suggests that using

```toml
[output.latex]
custom-template = "my-template.tex"
```

in `book.toml` should use a file `my-template.tex` in the same directory to the TOML file. However, I am not seeing that.

**Comment by jpgoldberg** [comment]
Oops. I must have just had a typo in my previous tests. It does work.

**Comment by lbeckman314** [comment]
Ah, I am glad it's working. I'll add some needed documentation for this feature.
